# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 180, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 180, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(360, 390, 151, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 50, 181, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 140, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 260, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 320, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 320, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 400, 35, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(422, 470, 71, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.add)
        self.pushButton_2.clicked.connect(self.sub)
        self.pushButton_3.clicked.connect(self.div)
        self.pushButton_4.clicked.connect(self.mul)
        self.pushButton_5.clicked.connect(self.clear)

    def add(self):
        try:
            text1 = int(self.lineEdit.text())
            text2 = int(self.lineEdit_2.text())
            ans = eval("text1+text2")
            self.textBrowser.setText(str(ans))
        except:
            self.textBrowser.setText("Wrong Input \n")
            self.textBrowser.setText("Enter only Integers")

    def sub(self):
        try:
            text1 = int(self.lineEdit.text())
            text2 = int(self.lineEdit_2.text())
            ans = eval("text1-text2")
            self.textBrowser.setText(str(ans))
        except:
            self.textBrowser.setText("Wrong Input \n")
            self.textBrowser.setText("Enter only Integers")

    def div(self):
        try:
            text1 = int(self.lineEdit.text())
            text2 = int(self.lineEdit_2.text())
            ans = eval("text1/text2")
            self.textBrowser.setText(str(ans))
        except:
            self.textBrowser.setText("Wrong Input \n")
            self.textBrowser.setText("Enter only Integers")

    def mul(self):
        try:
            text1 = int(self.lineEdit.text())
            text2 = int(self.lineEdit_2.text())
            ans = eval("text1*text2")
            self.textBrowser.setText(str(ans))
        except:
            self.textBrowser.setText("Wrong Input \n")
            self.textBrowser.setText("Enter only Integers")

    def clear(self):
        # clearing the label text
        self.textBrowser.setText("")
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "         CALCULATOR"))
        self.label_2.setText(_translate("MainWindow", "NUMBER 1"))
        self.label_3.setText(_translate("MainWindow", "Number 2"))
        self.pushButton_2.setText(_translate("MainWindow", "Sub"))
        self.pushButton_3.setText(_translate("MainWindow", "Div"))
        self.pushButton_4.setText(_translate("MainWindow", "Mul"))
        self.label_4.setText(_translate("MainWindow", "Result"))
        self.pushButton_5.setText(_translate("MainWindow", "clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
